services:
  mosquitto:
    build:
      context: .
    image: custom-mosquitto:latest
    restart: unless-stopped
    ports:
      - "${MQTT_PORT}:${MQTT_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    volumes:
      - ./certs:/mosquitto/certs
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    environment:
      - USERNAME
      - PASSWORD
      - HOSTNAME
      - LOG_TYPE=${LOG_TYPE}
      - MQTT_PORT=${MQTT_PORT}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
